### ISSUE TITLE
Feedback on API

### ISSUE THREAD

**Issue by drachs** [nlpcloud/nlpcloud-go#3]
Trying to use the Generation API - The API parameter blob seems really awkward to use.   All the parameters are pointers, which is a huge pain.  It's almost like the parameter structure should be generated from JSON but if so that's a trick I've never seen before.

The documentation could benefit hugely from a simple example here.   Also the documentation mentions tests but there doesn't seem to be any.

**Comment by juliensalinas** [comment]
Hello @drachs thanks so much for this feedback!

The unit and integration tests were removed from this lib several months ago, but we forgot to remove this from the README. Thanks for mentioning it, we just fixed it!

As far as pointers are concerned, they are only necessary for optional API parameters.
We are aware this is kind of a pain to set such pointers, but as far as we know this is common practice for optional values through a REST API in Go. If you can think of a better technique we will be more than happy to consider it!

Here is how you can set such pointers (here, setting an integer to 10):
```go
yourInt := new(int)
*yourInt = 10
```

Thanks @drachs , Looking forward to hearing from you.
